---
title: "Shiny Application and Reproducible Pitch"
author: "Dimitrios Andriopoulos"
date: "January 13, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Developing Data Products final project - Submission DA

An individual can earn income or have their savings vest by investing their money in interest-bearing products. There are three relevant parameters involved in estimating the values of an initial investment; namely, the interest rate $r$, the time horizon $t$, and the initial contribution $V_0$. 

The equation that estimates the value $V_{final}$ of the initial investment in the future is:

* $V_{final}=V_0 * (1+r)^{t}$

Using the above equation, I have created a Shinny App that automatically estimates the value $V$ given a users inputs; specifically, the interest rate $r$, the time horizon $t$, and the initial contribution $V_0$.

The user of the *Investment Growth* Shiny App will need to select an interest rate, a time horizon, and
an initial investment amount. 

The Shinny App estimates the value of their investment across different interest rates, time horizons, and initial invested amounts. Then, it plots the results to help the user identify the estimated value of their assets.

**Repository**

The Github repository contains the following files:

* ui.R
* server.R
* README.md

* Link for the repository: 

**Shinny App**

ui.R. server.R are the R files that generate the Shinny App, which can be found:

* Shinny App link: https://dandriopoulos.shinyapps.io/InvestmentGrowth/


## Developing Data Products final project - Coursera prompt

Below you can find the official prompt for this project:

This peer assessed assignment has two parts. First, you will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

### Your Shiny Application

Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.

* Deploy the application on Rstudio's shiny server
* Share the application link by pasting it into the provided text box
* Share your server.R and ui.R code on github
* The application must include the following:
* Some form of input (widget: textbox, radio button, checkbox, ...)
* Some operation on the ui input in sever.R
* Some reactive output displayed as a result of server calculations
* You must also include enough documentation so that a novice user could use your application.
* The documentation should be at the Shiny website itself. Do not post to an external link.

### Your Reproducible Pitch Presentation

OK, you've made your shiny app, now it's time to make your pitch. You get 5 slides (inclusive of the title slide)  to pitch a your app. You're going to create a web page using Slidify or Rstudio Presenter with an html5 slide deck.

* 5 slides to pitch our idea done in Slidify or Rstudio Presenter
* Your presentation pushed to github or Rpubs
* A link to your github or Rpubs presentation pasted into the provided text box
* Your presentation must satisfy the following
* It must be done in Slidify or Rstudio Presenter
* It must be 5 pages
* It must be hosted on github or Rpubs
* It must contained some embedded R code that gets run when slidifying the document

